mysqlurl: root:123456@tcp(mysql7:3306)/tour_jp?charset=utf8
mysqlmaxconnection: 20
imageurlshop: /imagesviews/
imageurlset: /imagesviews/
imageurldish: /imagesviews/
imagefolder: /self/prod/aaa/
urlh5employee: /ue/index.html
urlh5boss: /ub/index.html
urlh5customer: /uc/index.html
qrimgnameweb: qr_web.jpg
qrimgnamecustomer: qr_customer.jpg
qrimgnameemployee: qr_employee.jpg